name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js "18.x"
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - name: Run npm test with xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test
